apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-datascience-launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-datascience-launcher
  template:
    metadata:
      labels:
        app: kubernetes-datascience-launcher
    spec:
      containers:
      - image: registry.gitlab.com/kubernetes-data-science/kubernetes-data-science-spark/kubernetes-data-science-spark:latest
        name: hello-world

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-datascience-launcher
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "kubernetes-datascience-launcher"
    port: 8888
  selector:
    app: kubernetes-datascience-launcher
